### ISSUE TITLE
(node:117) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead. (Use `node --trace-deprecation ...` to show where the warning was created)

### ISSUE THREAD

**Issue by ItzMiracleOwO** [RadishTeam/RadishBot#52]
### 當前行為

Error:
(node:117) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

### 預期行為

(?)

**Comment by ItzMiracleOwO** [comment]
Full error
```
(node:106) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.
    at MessageEmbed.setFooter (/home/circleci/project/node_modules/discord.js/src/structures/MessageEmbed.js:439:17)
    at startbot (/home/circleci/project/bot.js:86:10)
    at Object.<anonymous> (/home/circleci/project/index.js:34:21)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by nk980113** [comment]
```diff
-         .setFooter(`${config.botName}`, 'https://cdn.discordapp.com/avatars/891195320690700299/7e70c4d7db63c7466488c8e9c6319307.png?size=80');
+         .setFooter({ text: `${config.botName}`, iconURL: 'https://cdn.discordapp.com/avatars/891195320690700299/7e70c4d7db63c7466488c8e9c6319307.png?size=80' });
```
[修改位置](https://github.com/RadishTeam/RadishBot/blob/main/bot.js#L86)
[Discord.js原始碼](https://github.com/discordjs/discord.js/blob/stable/src/structures/MessageEmbed.js#L431)
剩下的setFooter也這樣改

**Comment by nk980113** [comment]
@ItzMiracleOwO

**Comment by nk980113** [comment]
自己搞的

**Comment by nk980113** [comment]
沒必要再開著了
